spring:
  profiles:
    default: prod
  application:
    name: notification-service
  config:
    import: configserver:${CONFIG_SERVER:http://localhost:8888}
  cloud:
    config:
      fail-fast: true
