x-common-variables: &common-variables
  CONFIG_SERVER: http://config-server:8888
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
  LOKI_URL: http://loki:3100/loki/api/v1/push
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

services:
  prometheus:
    container_name: prometheus
    build:
      context: ./infrastructure/docker/prometheus
    ports:
      - "9090:9090"
    restart: no

  loki:
    container_name: loki
    build:
      context: ./infrastructure/docker/loki
    ports:
      - "3100:3100"
    restart: no

  grafana:
    container_name: grafana
    build:
      context: ./infrastructure/docker/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      prometheus:
        condition: service_started
      loki:
        condition: service_started
    restart: no

  zipkin:
    image: openzipkin/zipkin:3.5.1
    container_name: zipkin
    ports:
      - "9411:9411"
    restart: no

  config-server:
    container_name: config-server
    build:
      context: ./backend
      dockerfile: ./config-server/Dockerfile
    ports:
      - "8888:8888"
    environment:
      <<: *common-variables
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-your-jwt-ultra-secure-and-ultra-long-secret}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      loki:
        condition: service_started
      prometheus:
        condition: service_started
      zipkin:
        condition: service_started
    restart: no

  eureka-server:
    container_name: eureka-server
    build:
      context: ./backend
      dockerfile: ./eureka-server/Dockerfile
    ports:
      - "8761:8761"
    environment:
      <<: *common-variables
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      loki:
        condition: service_started
      prometheus:
        condition: service_started
      zipkin:
        condition: service_started
      config-server:
        condition: service_healthy
    restart: no

  db-quiz:
    image: postgres:17.5-alpine3.22
    container_name: db-quiz
    ports:
      - "5432:5432"
    environment:
      - TZ=Asia/Almaty
      - PGTZ=Asia/Almaty
      - POSTGRES_DB=quiz_db
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8 --auth-host=scram-sha-256 --auth-local=scram-sha-256
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-quiz-data:/var/lib/postgresql/data
    restart: no

  redis:
    image: redis:8.0.2-alpine3.21
    container_name: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: no

  quiz-service:
    container_name: quiz-service
    build:
      context: ./backend
      dockerfile: ./quiz-service/Dockerfile
    ports:
      - "8084:8084"
    environment:
      <<: *common-variables
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
      SPRING_R2DBC_URL: r2dbc:postgresql://db-quiz:5432/quiz_db
      SPRING_R2DBC_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_R2DBC_PASSWORD: ${POSTGRES_PASSWORD:-root}
      SPRING_FLYWAY_URL: jdbc:postgresql://db-quiz:5432/quiz_db
      SPRING_FLYWAY_USER: ${POSTGRES_USER:-postgres}
      SPRING_FLYWAY_PASSWORD: ${POSTGRES_PASSWORD:-root}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8084/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      loki:
        condition: service_started
      prometheus:
        condition: service_started
      zipkin:
        condition: service_started
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      db-quiz:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: no

  db-auth:
    image: postgres:17.5-alpine3.22
    container_name: db-auth
    ports:
      - "5433:5432"
    environment:
      - TZ=Asia/Almaty
      - PGTZ=Asia/Almaty
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8 --auth-host=scram-sha-256 --auth-local=scram-sha-256
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-auth-data:/var/lib/postgresql/data
    restart: no

  kafka:
    image: bitnami/kafka:4.0.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=INTERNAL://:29092,CLIENT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,CLIENT://host.docker.internal:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LOG_RETENTION_HOURS=168
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    restart: no

  auth-service:
    container_name: auth-service
    build:
      context: ./backend
      dockerfile: ./auth-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      <<: *common-variables
      SPRING_R2DBC_URL: r2dbc:postgresql://db-auth:5432/auth_db
      SPRING_R2DBC_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_R2DBC_PASSWORD: ${POSTGRES_PASSWORD:-root}
      SPRING_FLYWAY_URL: jdbc:postgresql://db-auth:5432/auth_db
      SPRING_FLYWAY_USER: ${POSTGRES_USER:-postgres}
      SPRING_FLYWAY_PASSWORD: ${POSTGRES_PASSWORD:-root}
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka:9092
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      loki:
        condition: service_started
      prometheus:
        condition: service_started
      zipkin:
        condition: service_started
      kafka:
        condition: service_started
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      db-auth:
        condition: service_healthy
    restart: no

  db-user:
    image: postgres:17.5-alpine3.22
    container_name: db-user
    ports:
      - "5434:5432"
    environment:
      - TZ=Asia/Almaty
      - PGTZ=Asia/Almaty
      - POSTGRES_DB=user_db
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8 --auth-host=scram-sha-256 --auth-local=scram-sha-256
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-user-data:/var/lib/postgresql/data
    restart: no

  user-service:
    container_name: user-service
    build:
      context: ./backend
      dockerfile: ./user-service/Dockerfile
    ports:
      - "8082:8082"
    environment:
      <<: *common-variables
      SPRING_R2DBC_URL: r2dbc:postgresql://db-user:5432/user_db
      SPRING_R2DBC_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_R2DBC_PASSWORD: ${POSTGRES_PASSWORD:-root}
      SPRING_FLYWAY_URL: jdbc:postgresql://db-user:5432/user_db
      SPRING_FLYWAY_USER: ${POSTGRES_USER:-postgres}
      SPRING_FLYWAY_PASSWORD: ${POSTGRES_PASSWORD:-root}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      loki:
        condition: service_started
      prometheus:
        condition: service_started
      zipkin:
        condition: service_started
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      db-user:
        condition: service_healthy
    restart: no

  notification-service:
    container_name: notification-service
    build:
      context: ./backend
      dockerfile: ./notification-service/Dockerfile
    ports:
      - "8083:8083"
    environment:
      <<: *common-variables
      SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS: kafka:9092
      MAILJET_PUBLIC_KEY: ${MAILJET_PUBLIC_KEY}
      MAILJET_PRIVATE_KEY: ${MAILJET_PRIVATE_KEY}
      MAILJET_SENDER_EMAIL: ${MAILJET_SENDER_EMAIL}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      loki:
        condition: service_started
      prometheus:
        condition: service_started
      zipkin:
        condition: service_started
      kafka:
        condition: service_started
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    restart: no

  api-gateway:
    container_name: api-gateway
    build:
      context: ./backend
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - "8765:8765"
    environment:
      <<: *common-variables
      SPRING_PROFILES_ACTIVE: dev
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8765/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      loki:
        condition: service_started
      prometheus:
        condition: service_started
      zipkin:
        condition: service_started
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      quiz-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy
    restart: no

  nginx:
    container_name: nginx
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8765
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      api-gateway:
        condition: service_healthy
    restart: no

volumes:
  db-quiz-data:
  db-auth-data:
  db-user-data:
