x-common-variables: &common-variables
  CONFIG_SERVER: http://config-server:8888
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
  LOKI_URL: http://loki:3100/loki/api/v1/push
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
  SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka:9092
  SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS: kafka:9092

services:
  prometheus:
    image: krivolapovdev/prometheus:latest
    container_name: prometheus
    expose:
      - 9090
    restart: unless-stopped

  loki:
    image: krivolapovdev/loki:latest
    container_name: loki
    expose:
      - 3100
    restart: unless-stopped

  grafana:
    image: krivolapovdev/grafana:latest
    container_name: grafana
    expose:
      - 3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      prometheus:
        condition: service_started
      loki:
        condition: service_started
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin:3.5.1
    container_name: zipkin
    expose:
      - 9411
    restart: unless-stopped

  config-server:
    image: krivolapovdev/config-server:latest
    container_name: config-server
    expose:
      - 8888
    environment:
      <<: *common-variables
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-your-jwt-ultra-secure-and-ultra-long-secret}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      loki:
        condition: service_started
      prometheus:
        condition: service_started
      zipkin:
        condition: service_started
    restart: unless-stopped

  eureka-server:
    image: krivolapovdev/eureka-server:latest
    container_name: eureka-server
    expose:
      - 8761
    environment:
      <<: *common-variables
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      loki:
        condition: service_started
      prometheus:
        condition: service_started
      zipkin:
        condition: service_started
      config-server:
        condition: service_healthy
    restart: unless-stopped

  db-quiz:
    image: postgres:17.5-alpine3.22
    container_name: db-quiz
    expose:
      - 5432
    environment:
      - TZ=Asia/Almaty
      - PGTZ=Asia/Almaty
      - POSTGRES_DB=quiz_db
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8 --auth-host=scram-sha-256 --auth-local=scram-sha-256
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-quiz-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:8.0.2-alpine3.21
    container_name: redis
    expose:
      - 6379
    command: [ "redis-server", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:4.0.0
    container_name: kafka
    expose:
      - 9092
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=INTERNAL://:29092,CLIENT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,INTERNAL://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LOG_RETENTION_HOURS=720
    volumes:
      - kafka-data:/bitnami/kafka
    restart: unless-stopped

  quiz-service:
    image: krivolapovdev/quiz-service:latest
    container_name: quiz-service
    expose:
      - 8084
    environment:
      <<: *common-variables
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
      SPRING_R2DBC_URL: r2dbc:postgresql://db-quiz:5432/quiz_db
      SPRING_R2DBC_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_R2DBC_PASSWORD: ${POSTGRES_PASSWORD:-root}
      SPRING_FLYWAY_URL: jdbc:postgresql://db-quiz:5432/quiz_db
      SPRING_FLYWAY_USER: ${POSTGRES_USER:-postgres}
      SPRING_FLYWAY_PASSWORD: ${POSTGRES_PASSWORD:-root}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8084/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      loki:
        condition: service_started
      prometheus:
        condition: service_started
      zipkin:
        condition: service_started
      kafka:
        condition: service_started
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      db-quiz:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  db-auth:
    image: postgres:17.5-alpine3.22
    container_name: db-auth
    expose:
      - 5432
    environment:
      - TZ=Asia/Almaty
      - PGTZ=Asia/Almaty
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8 --auth-host=scram-sha-256 --auth-local=scram-sha-256
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-auth-data:/var/lib/postgresql/data
    restart: unless-stopped

  auth-service:
    image: krivolapovdev/auth-service:latest
    container_name: auth-service
    expose:
      - 8081
    environment:
      <<: *common-variables
      SPRING_R2DBC_URL: r2dbc:postgresql://db-auth:5432/auth_db
      SPRING_R2DBC_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_R2DBC_PASSWORD: ${POSTGRES_PASSWORD:-root}
      SPRING_FLYWAY_URL: jdbc:postgresql://db-auth:5432/auth_db
      SPRING_FLYWAY_USER: ${POSTGRES_USER:-postgres}
      SPRING_FLYWAY_PASSWORD: ${POSTGRES_PASSWORD:-root}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      loki:
        condition: service_started
      prometheus:
        condition: service_started
      zipkin:
        condition: service_started
      kafka:
        condition: service_started
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      db-auth:
        condition: service_healthy
    restart: unless-stopped

  db-user:
    image: postgres:17.5-alpine3.22
    container_name: db-user
    expose:
      - 5432
    environment:
      - TZ=Asia/Almaty
      - PGTZ=Asia/Almaty
      - POSTGRES_DB=user_db
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8 --auth-host=scram-sha-256 --auth-local=scram-sha-256
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-user-data:/var/lib/postgresql/data
    restart: unless-stopped

  user-service:
    image: krivolapovdev/user-service:latest
    container_name: user-service
    expose:
      - 8082
    environment:
      <<: *common-variables
      SPRING_R2DBC_URL: r2dbc:postgresql://db-user:5432/user_db
      SPRING_R2DBC_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_R2DBC_PASSWORD: ${POSTGRES_PASSWORD:-root}
      SPRING_FLYWAY_URL: jdbc:postgresql://db-user:5432/user_db
      SPRING_FLYWAY_USER: ${POSTGRES_USER:-postgres}
      SPRING_FLYWAY_PASSWORD: ${POSTGRES_PASSWORD:-root}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      loki:
        condition: service_started
      prometheus:
        condition: service_started
      zipkin:
        condition: service_started
      kafka:
        condition: service_started
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      db-user:
        condition: service_healthy
    restart: unless-stopped

  notification-service:
    image: krivolapovdev/notification-service:latest
    container_name: notification-service
    expose:
      - 8083
    environment:
      <<: *common-variables
      MAILJET_PUBLIC_KEY: ${MAILJET_PUBLIC_KEY}
      MAILJET_PRIVATE_KEY: ${MAILJET_PRIVATE_KEY}
      MAILJET_SENDER_EMAIL: ${MAILJET_SENDER_EMAIL}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      loki:
        condition: service_started
      prometheus:
        condition: service_started
      zipkin:
        condition: service_started
      kafka:
        condition: service_started
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    restart: unless-stopped

  api-gateway:
    image: krivolapovdev/api-gateway:latest
    container_name: api-gateway
    expose:
      - 8765
    environment:
      <<: *common-variables
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8765/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      loki:
        condition: service_started
      prometheus:
        condition: service_started
      zipkin:
        condition: service_started
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      quiz-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    image: krivolapovdev/nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-ssl:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      api-gateway:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db-quiz-data:
  db-auth-data:
  db-user-data:
  redis-data:
  kafka-data:
  certbot-ssl:
  certbot-www:
