x-common-variables: &common-variables
  CONFIG_SERVER: http://config-server:8888
  EUREKA_SERVER: http://eureka-server:8761/eureka/

services:
  prometheus:
    image: prom/prometheus:v3.4.1
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:3.5.1
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - ./infrastructure/docker/loki/local-config.yml:/etc/loki/local-config.yml

  grafana:
    image: grafana/grafana:12.0.1
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
    volumes:
      - ./infrastructure/docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./infrastructure/docker/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./infrastructure/docker/grafana/dashboards:/etc/grafana/dashboards

  config-server:
    container_name: config-server
    build:
      context: .
      dockerfile: infrastructure/docker/config-server/Dockerfile
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8888:8888"
    depends_on:
      - grafana

  eureka-server:
    container_name: eureka-server
    build:
      context: .
      dockerfile: infrastructure/docker/eureka-server/Dockerfile
    restart: unless-stopped
    environment:
      <<: *common-variables
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy

  quiz-service:
    container_name: quiz-service
    build:
      context: .
      dockerfile: infrastructure/docker/quiz-service/Dockerfile
    restart: unless-stopped
    environment:
      <<: *common-variables
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_healthy

  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: infrastructure/docker/api-gateway/Dockerfile
    restart: unless-stopped
    environment:
      <<: *common-variables
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8765/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8765:8765"
    depends_on:
      quiz-service:
        condition: service_healthy
