global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8888' ]

  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8761' ]

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8765' ]

  - job_name: 'quiz-service'
    metrics_path: '/quiz-service/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8765' ]
