server:
  port: 8765
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: quiz-service
          uri: lb://quiz-service
          predicates:
            - Path=/api/v*/quizzes/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v*/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v*/users/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
