spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost"
              - "http://localhost:5173"
              - "http://code-output-quiz.local"
              - "http://www.code-output-quiz.local"
