server:
  port: 8765
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: quiz-service
          uri: lb://quiz-service
          predicates:
            - Path=/api/v*/quizzes/**
