spring:
  flyway:
    clean-disabled: false
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1
    enabled: true
springdoc:
  swagger-ui:
    path: /swagger
