spring:
  cloud:
    config:
      override-system-properties: false
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always

