spring:
  cloud:
    config:
      override-system-properties: false
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
jwt:
  secret-key: your-jwt-ultra-secure-and-ultra-long-secret
  access-token-expiration: 15m
  refresh-token-expiration: 7d
loki:
  url: http://localhost:3100/loki/api/v1/push
