management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, refresh
logging:
  config: classpath:logback-spring-prod.xml
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
