spring:
  cloud:
    config:
      override-system-properties: false
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, prometheus, metrics, beans
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
