server:
  port: 8083
spring:
  kafka:
    consumer:
      group-id: notification-service
mailjet:
  publicKey: ${MAILJET_PUBLIC_KEY}
  privateKey: ${MAILJET_PRIVATE_KEY}
  senderEmail: ${MAILJET_SENDER_EMAIL}
