server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger
spring:
  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        options:
          model: deepseek-chat
      base-url: https://api.deepseek.com
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/quiz_db
    username: postgres
    password: root
  flyway:
    url: jdbc:postgresql://localhost:5432/quiz_db
    locations: classpath:db/migration
    user: postgres
    password: root
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
