server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger
spring:
  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        options:
          model: deepseek-chat
      base-url: https://api.deepseek.com
