server:
  port: 8084
spring:
  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        options:
          model: deepseek-chat
      base-url: https://api.deepseek.com
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/quiz_db
    username: postgres
    password: root
  flyway:
    url: jdbc:postgresql://localhost:5432/quiz_db
    locations: classpath:db/migration
    user: postgres
    password: root
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    consumer:
      group-id: quiz-service
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.reactive.ReactiveUserDetailsServiceAutoConfiguration
