spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/krivolapovdev/code-output-quiz
          search-paths: backend/config-server/src/main/resources/configs
          default-label: main
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, refresh

