server:
  port: 8888
spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      access:
