server:
  port: 8888
spring:
  application:
    name: config-server
  profiles:
    default: prod
    group:
      dev:
        - native
  devtools:
    restart:
      enabled: false
loki:
  url: http://localhost:3100/loki/api/v1/push
