spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:backend/config-server/src/main/resources/configs
logging:
  config: classpath:logback-spring-dev.xml
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
