spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:backend/config-server/src/main/resources/configs
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1
    enabled: true
