name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make gradlew executable
        working-directory: backend
        run: chmod +x gradlew

      - name: Install backend dependencies
        working-directory: backend
        run: ./gradlew dependencies --no-daemon

      - name: Run backend tests
        working-directory: backend
        run: ./gradlew test --no-daemon
