name: Release from Changelog

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: tag
        run: echo "version=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"

      - name: Read changelog for this version
        id: changelog
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.tag.outputs.version }}
          path: ./CHANGELOG.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ steps.tag.outputs.version }}
          body: ${{ steps.changelog.outputs.changes }}
