FROM grafana/grafana:12.0.1

COPY provisioning/datasources /etc/grafana/provisioning/datasources

COPY provisioning/dashboards /etc/grafana/provisioning/dashboards

COPY dashboards /etc/grafana/dashboards
